package:
  name: pm_icecon
  version: "0.8.0"

source:
  path: ../

build:
  number: {{ environ.get('BUILD_NUMBER', 0) }}
  script: python -m pip install . --no-deps -vv
  preserve_egg_dir: True
  noarch: python

requirements:
  build:
    - python ~=3.10.12
    - numpy >=2.2.6

  run:
    - python ~=3.10.12
    - numpy >=2.2.6
    - h5py >=3.14
    - xarray  >=2025.6.1
    - netCDF4 >=1.7.2
    - cartopy >=0.25.0
    - click ~=8.2
    - loguru >=0.7.3
    - pydantic ~=1.9  # Definitely NOT compatible with pydantic 2.0 (!)
    - pandas ~=2.3
    - pyresample ~=1.31
    - pm_tb_data >=0.4.0
    - scipy ~=1.15

about:
  home: https://github.com/nsidc/pm_icecon
  license: MIT
  summary: sea ice concentration estimates from passive microwave data
