package:
  name: pm_icecon
  version: "0.1.2"

source:
  path: ../

build:
  number: {{ environ.get('BUILD_NUMBER', 0) }}
  script: python setup.py install
  preserve_egg_dir: True
  noarch: python

requirements:
  build:
    - python ~=3.10.12
    - numpy ~=1.22.4

  run:
    - python ~=3.10.12
    - numpy ~=1.22.4
    - h5py ~=3.8
    - xarray ~=2023.6
    - netCDF4 ~=1.6.3
    - cartopy ~=0.21
    - click ~=8.1
    - loguru ~=0.7
    - pydantic ~=1.9  # Definitely NOT compatible with pydantic 2.0 (!)
    - pandas ~=1.4.4
    - seaice ~=6.0
    - pyresample ~=1.27
    - pm_tb_data ~=0.1.1

about:
  home: https://github.com/nsidc/pm_icecon
  license: MIT
  summary: sea ice concentration estimates from passive microwave data
