name: pm_icecon
channels:
  - conda-forge
  - nsidc
  - nodefaults
dependencies:
  # Testing/utilities
  - black ~=22.3
  - flake8 ~=4.0
  - flake8-quotes ~=3.3
    # Can detect certain poor practices; black can't:
  - flake8-bugbear ~=22.4
  # Can detect "unnecessary" comprehensions; black can't:
  - flake8-comprehensions ~=3.9
  # Can check the "voice" of a docstring subject; black can't:
  - flake8-docstrings ~=1.6
  - invoke ~=1.7
  - isort ~=5.10
  - mypy ~=1.5
  - pytest ~=7.1
  - vulture ~=2.4
  # debugging/development tools
  - ipython
  - ipdb
  - bump2version
  # build tools
  - conda-build ~=3.23.3
  - anaconda-client

  # Runtime dependencies
  # NOTE: these should be kept in sync with those in `recipe/meta.yaml`.
  - python ~=3.10.12
  - numpy ~=1.22.4
  - h5py ~=3.6
  - xarray ~=2023.6
  - netCDF4 ~=1.6.3
  - cartopy ~=0.21
  - click ~=8.1
  - loguru ~=0.7
  - pydantic ~=1.9  # Definitely NOT compatible with pydantic 2.0 (!)
  - pandas ~=1.4.4
  - seaice ~=6.0
  - pyresample ~=1.27
  - pm_tb_data ~=0.1.0
