name: cdr_amsr2
channels:
  - conda-forge
  - nsidc
  - nodefaults
dependencies:
  # Testing/utilities
  - black ~=22.3
  - flake8 ~=4.0
  - flake8-quotes ~=3.3
    # Can detect certain poor practices; black can't:
  - flake8-bugbear ~=22.4
  # Can detect "unnecessary" comprehensions; black can't:
  - flake8-comprehensions ~=3.9
  # Can check the "voice" of a docstring subject; black can't:
  - flake8-docstrings ~=1.6
  - invoke ~=1.7
  - isort ~=5.10
  - mypy ~=0.961
  - pytest ~=7.1
  - vulture ~=2.4
  # debugging/development tools
  - ipython
  - ipdb

  # Runtime dependencies
  - python ~=3.10.4
  - numpy ~=1.22.3
  - h5py ~=3.6
  - xarray ~=2022.3
  - netCDF4 ~=1.5.8
  - cartopy ~=0.20
  - click ~=8.1
  - loguru ~=0.6
  - pydantic ~=1.9
  - pandas ~=1.4.2
  - seaice ~=5.0.0
  - pyresample ~=1.25
