name: pm_icecon
channels:
  - conda-forge
  - nsidc
  - nodefaults
dependencies:
  - invoke ~=1.7
  - isort ~=5.10
  - mypy ~=1.5
  - pytest ~=7.1
  - vulture ~=2.4
  # debugging/development tools
  - ipython
  - ipdb
  - bump2version
  - pre-commit
  - conda-lock
  # build tools
  - conda-build ~=3.23.3
  - anaconda-client

  # Runtime dependencies
  # NOTE: these should be kept in sync with those in `recipe/meta.yaml`.
  - python ~=3.10.12
  - numpy ~=1.22.4
  - h5py ~=3.6
  - xarray ~=2023.6
  - netCDF4 ~=1.6.3
  - cartopy ~=0.21
  - click ~=8.1
  - loguru ~=0.7
  - pydantic ~=1.9  # Definitely NOT compatible with pydantic 2.0 (!)
  - pandas ~=1.4.4
  - pyresample ~=1.27
  - pm_tb_data ~=0.1.2
  - scipy ~=1.8.1
