name: pm_icecon
channels:
  - conda-forge
  - nsidc
  - nodefaults
dependencies:
  - invoke
  - isort
  - mypy ~=1.17.1
  - pytest
  - pytest-cov
  - vulture
  # debugging/development tools
  - ipython
  - ipdb
  - bump-my-version
  - pre-commit
  - conda-lock
  # build tools
  - conda-build
  - anaconda-client
  - boa

  # Runtime dependencies
  # NOTE: these should be kept in sync with those in `recipe/meta.yaml`.
  - python ~=3.10.12
  - numpy >=2.2.6
  - h5py >=3.14
  - xarray  >=2025.6.1
  - netCDF4 >=1.7.2
  - cartopy >=0.25.0
  - click ~=8.2
  - loguru >=0.7.3
  - pydantic ~=1.9  # Definitely NOT compatible with pydantic 2.0 (!)
  - pandas ~=2.3
  - pyresample ~=1.31
  - pm_tb_data >=0.6.0
  - scipy ~=1.15
