version: 2

conda-setup: &conda-setup
  working_directory: ~/cdr_amsr2
  docker:
    - image: continuumio/miniconda3:4.10.3

docker-setup: &docker-setup
  docker:
    - image: docker:17.05.0-ce-git
  working_directory: ~/cdr_amsr2
  # 1 vCPU, 2GB RAM: https://circleci.com/docs/2.0/configuration-reference/#resourceclass
  resource_class: small

jobs:
  test:
    <<: *conda-setup
    steps:
      - checkout
      - run:
          name: Configure Conda
          command: conda env create -f environment.yml
      - run:
          name: Run tests
          command: |
            source activate cdr_amsr2

            invoke test.all


workflows:
  version: 2
  run-tests:
    jobs:
      - test:
          filters:
            tags:
               only: /.*/
