
        character*120 dir_anc,dir_tbs
c       Original (Goddard) hardcoded file locations
c       DATA dir_anc/'/Users/rgersten/NRTSI/FORTRAN_PROGS_SB2/For_NSIDC/ANCILLARY/'/
c       DATA dir_tbs/'/Users/rgersten/TBS/NRT/2018/'/

c       Original (ScottS laptop) hardcoded file locations
c       DATA dir_anc/'/home/scotts/sic_py/bt_orig/SB2_NRT_programs/ANCILLARY/'/
c       DATA dir_tbs/'/home/scotts/sic_py/bt_orig/SB2_NRT_programs/orig_input_tbs/'/

        DATA dir_anc/'../SB2_NRT_programs/ANCILLARY/'/
        DATA dir_tbs/'../SB2_NRT_programs/orig_input_tbs/'/
